use CosmeticsShop;
CREATE TABLE PRODUCTS (
ProductID int NOT NULL,
Name nvarchar(50) NOT NULL,
Description nvarchar(150) NOT NULL,
Price int NOT NULL,
Category nvarchar(50) NOT NULL,
Image nvarchar(50),
CONSTRAINT PK_PRODUCTS PRIMARY KEY (ProductID)
)

 CREATE TABLE CLIENT (
ClientID int NOT NULL,
Name nvarchar(50) NOT NULL,
LastName nvarchar(50) NOT NULL,
Address nvarchar(50) NOT NULL,
Email nvarchar(50) NOT NULL,
Phone int NOT NULL,
CONSTRAINT PK_CLIENT PRIMARY KEY (ClientID)
)
 CREATE TABLE ORDERS (
OrderID int NOT NULL,
Client_ID int NOT NULL CONSTRAINT FK_ORDERS_Client_ID FOREIGN KEY REFERENCES CLIENT(ClientID) ON UPDATE CASCADE,
DateOrder date NOT NULL,
Statuss nvarchar(50) NOT NULL,
CONSTRAINT PK_ORDERS PRIMARY KEY (OrderID)
)

CREATE TABLE ORDER_PRODUCTS (
OrderID int NOT NULL CONSTRAINT FK_ORDER_PRODUCTS_OrderID FOREIGN KEY REFERENCES ORDERS(OrderID) ON DELETE NO ACTION,
ProductID int NOT NULL CONSTRAINT FK_ORDER_PRODUCTS_ID FOREIGN KEY REFERENCES PRODUCTS(ProductID) ON UPDATE CASCADE,
Quantity int NOT NULL,
CONSTRAINT PK_ORDERED PRIMARY KEY (OrderID)
)